<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <PackageIcon>logo.jpg</PackageIcon>
    <PackageId>Durant</PackageId>
    <Title>Durant</Title>
    <ApplicationIcon>logo.ico</ApplicationIcon>
    <AssemblyName>Durant</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="632 1.jpg" />
    <None Remove="632 1.png" />
    <None Remove="632 2.png" />
    <None Remove="632 3.png" />
    <None Remove="ambiente.png" />
    <None Remove="Arrow right-circle.png" />
    <None Remove="image 2.png" />
    <None Remove="image 4.png" />
    <None Remove="image 8.png" />
    <None Remove="logo.ico" />
    <None Remove="pastos.png" />
    <None Remove="recursos\agua.png" />
    <None Remove="recursos\ambiente.png" />
    <None Remove="recursos\Arrow right-circle.png" />
    <None Remove="recursos\depredador.png" />
    <None Remove="recursos\FondoEstadisticas.png" />
    <None Remove="recursos\hormiga1.png" />
    <None Remove="recursos\hormiga2.png" />
    <None Remove="recursos\hormiga3.png" />
    <None Remove="recursos\HormigaSalir.png" />
    <None Remove="recursos\pastos.png" />
    <None Remove="recursos\poza.png" />
    <None Remove="recursos\recursos.png" />
    <None Remove="recursos\salir.png" />
    <None Remove="recursos\stone.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="logo.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="logo.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="recursos\agua.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="recursos\ambiente.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="recursos\Arrow right-circle.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="recursos\depredador.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="recursos\FondoEstadisticas.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="recursos\hormiga1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="recursos\hormiga2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="recursos\hormiga3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="recursos\HormigaSalir.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="recursos\pastos.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="recursos\poza.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="recursos\recursos.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="recursos\salir.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="recursos\stone.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="logo.jpg">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
